# Generated by Django 4.2.5 on 2023-10-02 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_tag_user_role_task"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="due_to",
            new_name="deadline_at",
        ),
    ]
